describe('ReST accessor /api/users', function() {

	it('GET /api/users', function(done) {
		// Auto-generated by doop-cli
		app.test.agent.get(app.config.url + '/api/users')
			.end(function(err, rs) {
				if (res.body.error) return done(res.body.error);
				expect(err).to.not.be.ok;

				res.body.forEach(function(i) {
					expect(i).to.have.property('username');
					expect(i.username).to.be.a.string;
					expect(i).to.have.property('email');
					expect(i.email).to.be.a.string;
					expect(i).to.not.have.property('_passhash');
					expect(i).to.not.have.property('_passhash2');
					expect(i).to.not.have.property('_passsalt');
					expect(i).to.have.property('name');
					expect(i.name).to.be.a.string;
					expect(i).to.have.property('status');
					expect(i.status).to.be.a.string;
					expect(i).to.have.property('role');
					expect(i.role).to.be.a.string;
					expect(i).to.have.property('token');
					expect(i.token).to.be.a.string;
					expect(i).to.have.property('settings');
					expect(i).to.have.property('created');
					expect(i.created).to.be.a.date;
					expect(i).to.have.property('lastLogin');
					expect(i.lastLogin).to.be.a.date;
					expect(i).to.have.property('dob');
					expect(i.dob).to.be.a.date;
					expect(i).to.have.property('_id');

					done();
				});
			});
		});
	});

});