#!/bin/bash
# Re-Deploy the server
# Usage: ~/redeploy [--skip-build]
#
# --skip-build      Do not pull from git / rebuild gulp, just restart the process

# Stop on errors
set -euo pipefail

if [ -d /root/doop.mfdc.dev ]; then
	echo "Performing DEV redeployment"
	cd /root/doop.mfdc.dev
else
	echo "Unknown server profile"
	exit
fi

if [ "${1:-0}" == "--skip-build" ]; then
	echo "Skipping Git + Gulp"
else
	echo "Pre-deploying via Gulp..."
	gulp preDeploy

	echo "Pulling latest Git repo..."
	git pull

	echo "Installing NPM packages..."
	npm ci

	echo "Building via Gulp..."
	gulp build

	echo "post-deploying via Gulp..."
	gulp postDeploy
fi

# Force Chalk color support within PM2
export FORCE_COLOR=2

if [[ `pm2 show doop-a >/dev/null 2>/dev/null; echo "$?"` == "1" ]]; then
	echo "Starting PM2 process for the first time..."
	pm2 start --name 'doop-a' --time server/index.js -- -e production -o port=10001 -o papertrail.program=doop-a -o cache.cleanAuto=true -o mongo.migration=true
	pm2 start --name 'doop-b' --time server/index.js -- -e production -o port=10002 -o papertrail.program=doop-b
	pm2 start --name 'doop-c' --time server/index.js -- -e production -o port=10003 -o papertrail.program=doop-c
	pm2 start --name 'doop-d' --time server/index.js -- -e production -o port=10004 -o papertrail.program=doop-d
else
	echo "Rebooting PM2 process..."
	pm2 restart --wait-ready --listen-timeout=10000 doop-a doop-b doop-c doop-d
fi

echo "done."
